apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
patchesStrategicMerge:
  - patches/argocd.yaml
patchesJson6902:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: prometheus
    patch: |-
      - op: add
        path: /spec/source/helm/valueFiles/-
        value: "https://github.com/valerauko/argonaut/components/prometheus/overlays/prd/values.yaml"
